/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as TourSlugRouteImport } from './routes/tour.$slug'
import { Route as OwnerPropertiesNewRouteImport } from './routes/owner.properties.new'
import { Route as OwnerPropertiesIdCalendarRouteImport } from './routes/owner.properties.$id.calendar'
import { Route as OwnerPropertiesIdEditRouteImport } from './routes/owner.properties.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/admin/cities',
  path: '/admin/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TourSlugRoute = TourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesNewRoute = OwnerPropertiesNewRouteImport.update({
  id: '/owner/properties/new',
  path: '/owner/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesIdCalendarRoute =
  OwnerPropertiesIdCalendarRouteImport.update({
    id: '/owner/properties/$id/calendar',
    path: '/owner/properties/$id/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerPropertiesIdEditRoute = OwnerPropertiesIdEditRouteImport.update({
  id: '/owner/properties/$id/edit',
  path: '/owner/properties/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/tours': typeof ToursRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/owner/properties/$id/calendar': typeof OwnerPropertiesIdCalendarRoute
  '/owner/properties/$id/edit': typeof OwnerPropertiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/tours': typeof ToursRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/owner/properties/$id/calendar': typeof OwnerPropertiesIdCalendarRoute
  '/owner/properties/$id/edit': typeof OwnerPropertiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/tours': typeof ToursRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/owner/properties/$id/calendar': typeof OwnerPropertiesIdCalendarRoute
  '/owner/properties/$id/edit': typeof OwnerPropertiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/destinations'
    | '/favorites'
    | '/search'
    | '/tours'
    | '/account/notifications'
    | '/admin/cities'
    | '/property/$slug'
    | '/tour/$slug'
    | '/account/'
    | '/admin/'
    | '/owner/'
    | '/owner/properties/new'
    | '/owner/properties/$id/calendar'
    | '/owner/properties/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/destinations'
    | '/favorites'
    | '/search'
    | '/tours'
    | '/account/notifications'
    | '/admin/cities'
    | '/property/$slug'
    | '/tour/$slug'
    | '/account'
    | '/admin'
    | '/owner'
    | '/owner/properties/new'
    | '/owner/properties/$id/calendar'
    | '/owner/properties/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/destinations'
    | '/favorites'
    | '/search'
    | '/tours'
    | '/account/notifications'
    | '/admin/cities'
    | '/property/$slug'
    | '/tour/$slug'
    | '/account/'
    | '/admin/'
    | '/owner/'
    | '/owner/properties/new'
    | '/owner/properties/$id/calendar'
    | '/owner/properties/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DestinationsRoute: typeof DestinationsRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  ToursRoute: typeof ToursRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  PropertySlugRoute: typeof PropertySlugRoute
  TourSlugRoute: typeof TourSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerPropertiesNewRoute: typeof OwnerPropertiesNewRoute
  OwnerPropertiesIdCalendarRoute: typeof OwnerPropertiesIdCalendarRoute
  OwnerPropertiesIdEditRoute: typeof OwnerPropertiesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/admin/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$slug': {
      id: '/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/new': {
      id: '/owner/properties/new'
      path: '/owner/properties/new'
      fullPath: '/owner/properties/new'
      preLoaderRoute: typeof OwnerPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/$id/calendar': {
      id: '/owner/properties/$id/calendar'
      path: '/owner/properties/$id/calendar'
      fullPath: '/owner/properties/$id/calendar'
      preLoaderRoute: typeof OwnerPropertiesIdCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/$id/edit': {
      id: '/owner/properties/$id/edit'
      path: '/owner/properties/$id/edit'
      fullPath: '/owner/properties/$id/edit'
      preLoaderRoute: typeof OwnerPropertiesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DestinationsRoute: DestinationsRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  ToursRoute: ToursRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  PropertySlugRoute: PropertySlugRoute,
  TourSlugRoute: TourSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerPropertiesNewRoute: OwnerPropertiesNewRoute,
  OwnerPropertiesIdCalendarRoute: OwnerPropertiesIdCalendarRoute,
  OwnerPropertiesIdEditRoute: OwnerPropertiesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
