/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountBookingsRouteImport } from './routes/account.bookings'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerCalendarRouteImport } from './routes/owner.calendar'
import { Route as OwnerProfileRouteImport } from './routes/owner.profile'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as TourSlugRouteImport } from './routes/tour.$slug'
import { Route as OwnerPropertiesIndexRouteImport } from './routes/owner.properties.index'
import { Route as OwnerPropertiesNewRouteImport } from './routes/owner.properties.new'
import { Route as OwnerToursNewRouteImport } from './routes/owner.tours.new'
import { Route as OwnerPropertiesIdCalendarRouteImport } from './routes/owner.properties.$id.calendar'
import { Route as OwnerPropertiesIdEditRouteImport } from './routes/owner.properties.$id.edit'
import { Route as OwnerPropertiesIdPricingRouteImport } from './routes/owner.properties.$id.pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/account/bookings',
  path: '/account/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/admin/cities',
  path: '/admin/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/owner/analytics',
  path: '/owner/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner/bookings',
  path: '/owner/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerCalendarRoute = OwnerCalendarRouteImport.update({
  id: '/owner/calendar',
  path: '/owner/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProfileRoute = OwnerProfileRouteImport.update({
  id: '/owner/profile',
  path: '/owner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TourSlugRoute = TourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesIndexRoute = OwnerPropertiesIndexRouteImport.update({
  id: '/owner/properties/',
  path: '/owner/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesNewRoute = OwnerPropertiesNewRouteImport.update({
  id: '/owner/properties/new',
  path: '/owner/properties/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerToursNewRoute = OwnerToursNewRouteImport.update({
  id: '/owner/tours/new',
  path: '/owner/tours/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesIdCalendarRoute =
  OwnerPropertiesIdCalendarRouteImport.update({
    id: '/owner/properties/$id/calendar',
    path: '/owner/properties/$id/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const OwnerPropertiesIdEditRoute = OwnerPropertiesIdEditRouteImport.update({
  id: '/owner/properties/$id/edit',
  path: '/owner/properties/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertiesIdPricingRoute =
  OwnerPropertiesIdPricingRouteImport.update({
    id: '/owner/properties/$id/pricing',
    path: '/owner/properties/$id/pricing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/calendar': typeof OwnerCalendarRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/p/$slug': typeof PSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/owner/tours/new': typeof OwnerToursNewRoute
  '/owner/properties/': typeof OwnerPropertiesIndexRoute
  '/owner/properties/$id/calendar': typeof OwnerPropertiesIdCalendarRoute
  '/owner/properties/$id/edit': typeof OwnerPropertiesIdEditRoute
  '/owner/properties/$id/pricing': typeof OwnerPropertiesIdPricingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/calendar': typeof OwnerCalendarRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/p/$slug': typeof PSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/owner/tours/new': typeof OwnerToursNewRoute
  '/owner/properties': typeof OwnerPropertiesIndexRoute
  '/owner/properties/$id/calendar': typeof OwnerPropertiesIdCalendarRoute
  '/owner/properties/$id/edit': typeof OwnerPropertiesIdEditRoute
  '/owner/properties/$id/pricing': typeof OwnerPropertiesIdPricingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/destinations': typeof DestinationsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tours': typeof ToursRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/calendar': typeof OwnerCalendarRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/p/$slug': typeof PSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/owner/tours/new': typeof OwnerToursNewRoute
  '/owner/properties/': typeof OwnerPropertiesIndexRoute
  '/owner/properties/$id/calendar': typeof OwnerPropertiesIdCalendarRoute
  '/owner/properties/$id/edit': typeof OwnerPropertiesIdEditRoute
  '/owner/properties/$id/pricing': typeof OwnerPropertiesIdPricingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/destinations'
    | '/favorites'
    | '/help'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/tours'
    | '/account/bookings'
    | '/account/notifications'
    | '/admin/cities'
    | '/admin/pages'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/calendar'
    | '/owner/profile'
    | '/p/$slug'
    | '/property/$slug'
    | '/tour/$slug'
    | '/account/'
    | '/admin/'
    | '/owner/'
    | '/owner/properties/new'
    | '/owner/tours/new'
    | '/owner/properties/'
    | '/owner/properties/$id/calendar'
    | '/owner/properties/$id/edit'
    | '/owner/properties/$id/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/destinations'
    | '/favorites'
    | '/help'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/tours'
    | '/account/bookings'
    | '/account/notifications'
    | '/admin/cities'
    | '/admin/pages'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/calendar'
    | '/owner/profile'
    | '/p/$slug'
    | '/property/$slug'
    | '/tour/$slug'
    | '/account'
    | '/admin'
    | '/owner'
    | '/owner/properties/new'
    | '/owner/tours/new'
    | '/owner/properties'
    | '/owner/properties/$id/calendar'
    | '/owner/properties/$id/edit'
    | '/owner/properties/$id/pricing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/destinations'
    | '/favorites'
    | '/help'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/tours'
    | '/account/bookings'
    | '/account/notifications'
    | '/admin/cities'
    | '/admin/pages'
    | '/owner/analytics'
    | '/owner/bookings'
    | '/owner/calendar'
    | '/owner/profile'
    | '/p/$slug'
    | '/property/$slug'
    | '/tour/$slug'
    | '/account/'
    | '/admin/'
    | '/owner/'
    | '/owner/properties/new'
    | '/owner/tours/new'
    | '/owner/properties/'
    | '/owner/properties/$id/calendar'
    | '/owner/properties/$id/edit'
    | '/owner/properties/$id/pricing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DestinationsRoute: typeof DestinationsRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToursRoute: typeof ToursRoute
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminPagesRoute: typeof AdminPagesRoute
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerCalendarRoute: typeof OwnerCalendarRoute
  OwnerProfileRoute: typeof OwnerProfileRoute
  PSlugRoute: typeof PSlugRoute
  PropertySlugRoute: typeof PropertySlugRoute
  TourSlugRoute: typeof TourSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  OwnerPropertiesNewRoute: typeof OwnerPropertiesNewRoute
  OwnerToursNewRoute: typeof OwnerToursNewRoute
  OwnerPropertiesIndexRoute: typeof OwnerPropertiesIndexRoute
  OwnerPropertiesIdCalendarRoute: typeof OwnerPropertiesIdCalendarRoute
  OwnerPropertiesIdEditRoute: typeof OwnerPropertiesIdEditRoute
  OwnerPropertiesIdPricingRoute: typeof OwnerPropertiesIdPricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/account/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/admin/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/owner/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/calendar': {
      id: '/owner/calendar'
      path: '/owner/calendar'
      fullPath: '/owner/calendar'
      preLoaderRoute: typeof OwnerCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/profile': {
      id: '/owner/profile'
      path: '/owner/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof OwnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$slug': {
      id: '/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/': {
      id: '/owner/properties/'
      path: '/owner/properties'
      fullPath: '/owner/properties/'
      preLoaderRoute: typeof OwnerPropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/new': {
      id: '/owner/properties/new'
      path: '/owner/properties/new'
      fullPath: '/owner/properties/new'
      preLoaderRoute: typeof OwnerPropertiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/tours/new': {
      id: '/owner/tours/new'
      path: '/owner/tours/new'
      fullPath: '/owner/tours/new'
      preLoaderRoute: typeof OwnerToursNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/$id/calendar': {
      id: '/owner/properties/$id/calendar'
      path: '/owner/properties/$id/calendar'
      fullPath: '/owner/properties/$id/calendar'
      preLoaderRoute: typeof OwnerPropertiesIdCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/$id/edit': {
      id: '/owner/properties/$id/edit'
      path: '/owner/properties/$id/edit'
      fullPath: '/owner/properties/$id/edit'
      preLoaderRoute: typeof OwnerPropertiesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/properties/$id/pricing': {
      id: '/owner/properties/$id/pricing'
      path: '/owner/properties/$id/pricing'
      fullPath: '/owner/properties/$id/pricing'
      preLoaderRoute: typeof OwnerPropertiesIdPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DestinationsRoute: DestinationsRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToursRoute: ToursRoute,
  AccountBookingsRoute: AccountBookingsRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminPagesRoute: AdminPagesRoute,
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerCalendarRoute: OwnerCalendarRoute,
  OwnerProfileRoute: OwnerProfileRoute,
  PSlugRoute: PSlugRoute,
  PropertySlugRoute: PropertySlugRoute,
  TourSlugRoute: TourSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  OwnerPropertiesNewRoute: OwnerPropertiesNewRoute,
  OwnerToursNewRoute: OwnerToursNewRoute,
  OwnerPropertiesIndexRoute: OwnerPropertiesIndexRoute,
  OwnerPropertiesIdCalendarRoute: OwnerPropertiesIdCalendarRoute,
  OwnerPropertiesIdEditRoute: OwnerPropertiesIdEditRoute,
  OwnerPropertiesIdPricingRoute: OwnerPropertiesIdPricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
